/**
 * Diydor dizayn tizimi — Stitch dizaynlaridan ko'chirilgan Material 3 token'lari.
 * Bu yagona manba: dizayn <-> kod birligi.
 */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'secondary-container': '#e6dedd',
        'primary-container': '#ff7a70',
        'on-secondary-fixed': '#1e1b1b',
        'surface-container': '#f0edef',
        'surface-warm': '#FFFFFF',
        'surface-bright': '#fcf8fb',
        'surface-container-low': '#f6f3f5',
        'on-tertiary-container': '#003779',
        'error-container': '#ffdad6',
        background: '#fcf8fb',
        'surface-tint': '#a73833',
        'secondary-fixed': '#e8e1e0',
        'on-surface': '#1b1b1d',
        'surface-container-highest': '#e4e2e4',
        'tertiary-container': '#71a2ff',
        'primary-fixed': '#ffdad6',
        'secondary-fixed-dim': '#ccc5c4',
        'on-tertiary': '#ffffff',
        surface: '#fcf8fb',
        outline: '#8b716e',
        'inverse-surface': '#303032',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#001a41',
        'on-error-container': '#93000a',
        'on-primary-container': '#721112',
        'surface-variant': '#e4e2e4',
        'on-primary-fixed': '#410003',
        'on-background': '#1b1b1d',
        tertiary: '#005bc1',
        'on-tertiary-fixed-variant': '#004493',
        'on-surface-variant': '#57423f',
        'coral-deep': '#E86358',
        'surface-dim': '#dcd9dc',
        'inverse-on-surface': '#f3f0f2',
        'on-secondary-container': '#666161',
        'surface-subtle': '#F2F2F7',
        'primary-fixed-dim': '#ffb3ac',
        'on-secondary-fixed-variant': '#4a4645',
        'platinum-dark': '#121212',
        'inverse-primary': '#ffb3ac',
        'outline-variant': '#dec0bc',
        'tertiary-fixed-dim': '#adc6ff',
        'tertiary-fixed': '#d8e2ff',
        'surface-container-high': '#eae7ea',
        secondary: '#625d5d',
        'on-primary-fixed-variant': '#86211e',
        primary: '#a73833',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        success: '#34C759',
        'success-container': '#E5F9E9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        button: '16px',
        full: '9999px',
      },
      spacing: {
        gutter: '12px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'safe-bottom': '34px',
        'margin-main': '16px',
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        'label-sm': ['Manrope'],
        'label-md': ['Manrope'],
        'label-lg': ['Manrope'],
        'label-caps': ['Manrope'],
        'title-md': ['Manrope'],
        'title-lg': ['Manrope'],
        'headline-lg': ['Manrope'],
        'headline-lg-mobile': ['Manrope'],
        'headline-md': ['Manrope'],
        'body-lg': ['Manrope'],
        'body-md': ['Manrope'],
      },
      fontSize: {
        'label-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-lg': ['34px', { lineHeight: '41px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '20px', fontWeight: '400' }],
      },
      boxShadow: {
        ambient: '0px 10px 30px rgba(0,0,0,0.08)',
        lift: '0px 15px 40px rgba(0,0,0,0.12)',
        glow: '0 0 40px rgba(52, 199, 89, 0.4)',
      },
    },
  },
  plugins: [],
};
