/**
 * Diydor dizayn tizimi — "Issiq editorial" (Hinge uslubi) + soft clay.
 * Ranglar CSS o'zgaruvchilariga (src/index.css :root / .dark) bog'langan —
 * shu sabab DARK MODE barcha 21 ekranda avtomatik ishlaydi, va alpha
 * utility'lar (bg-primary/20) saqlanadi: rgb(var(--c-x) / <alpha-value>).
 *
 * Falsafa: issiq krem yuzalar, boyitilgan terracotta, serif sarlavhalar
 * (Fraunces) + toza sans (Manrope). Tinch, ishonchli, premium his.
 */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background': 'rgb(var(--c-background) / <alpha-value>)',
        'surface': 'rgb(var(--c-surface) / <alpha-value>)',
        'surface-warm': 'rgb(var(--c-surface-warm) / <alpha-value>)',
        'surface-bright': 'rgb(var(--c-surface-bright) / <alpha-value>)',
        'surface-subtle': 'rgb(var(--c-surface-subtle) / <alpha-value>)',
        'surface-dim': 'rgb(var(--c-surface-dim) / <alpha-value>)',
        'surface-variant': 'rgb(var(--c-surface-variant) / <alpha-value>)',
        'surface-tint': 'rgb(var(--c-surface-tint) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--c-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--c-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--c-surface-container-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
        'on-background': 'rgb(var(--c-on-background) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        'outline': 'rgb(var(--c-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--c-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--c-inverse-primary) / <alpha-value>)',
        'primary': 'rgb(var(--c-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--c-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--c-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--c-on-primary-container) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--c-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--c-primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--c-on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--c-on-primary-fixed-variant) / <alpha-value>)',
        'coral-deep': 'rgb(var(--c-coral-deep) / <alpha-value>)',
        'secondary': 'rgb(var(--c-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--c-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--c-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--c-on-secondary-container) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--c-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--c-secondary-fixed-dim) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--c-on-secondary-fixed) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--c-on-secondary-fixed-variant) / <alpha-value>)',
        'tertiary': 'rgb(var(--c-tertiary) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--c-on-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--c-tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--c-on-tertiary-container) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--c-tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--c-tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--c-on-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--c-on-tertiary-fixed-variant) / <alpha-value>)',
        'success': 'rgb(var(--c-success) / <alpha-value>)',
        'success-container': 'rgb(var(--c-success-container) / <alpha-value>)',
        'error': 'rgb(var(--c-error) / <alpha-value>)',
        'on-error': 'rgb(var(--c-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--c-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--c-on-error-container) / <alpha-value>)',
        'platinum-dark': 'rgb(var(--c-platinum-dark) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        button: '16px',
        card: '24px',
        sheet: '28px',
        full: '9999px',
      },
      spacing: {
        gutter: '12px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'safe-bottom': '34px',
        'margin-main': '16px',
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        display: ['Fraunces', 'Georgia', 'serif'],
        serif: ['Fraunces', 'Georgia', 'serif'],
        'display-lg': ['Fraunces', 'Georgia', 'serif'],
        'headline-lg': ['Fraunces', 'Georgia', 'serif'],
        'headline-lg-mobile': ['Fraunces', 'Georgia', 'serif'],
        'headline-md': ['Fraunces', 'Georgia', 'serif'],
        'title-md': ['Manrope'],
        'title-lg': ['Manrope'],
        'label-sm': ['Manrope'],
        'label-md': ['Manrope'],
        'label-lg': ['Manrope'],
        'label-caps': ['Manrope'],
        'body-lg': ['Manrope'],
        'body-md': ['Manrope'],
      },
      fontSize: {
        'label-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'display-lg': ['42px', { lineHeight: '46px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg': ['34px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '20px', fontWeight: '400' }],
      },
      boxShadow: {
        ambient: '0 10px 30px rgba(90,45,25,0.10)',
        lift: '0 18px 44px rgba(90,45,25,0.16)',
        card: '0 4px 24px rgba(120,72,40,0.10)',
        warm: '0 10px 24px rgba(190,74,46,0.28)',
        glow: '0 0 40px rgba(76,154,106,0.40)',
      },
    },
  },
  plugins: [],
};
